namespace DataVisualizer {
	partial class DataVisualizer {
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent() {
			this.tabControl1 = new System.Windows.Forms.TabControl();
			this.plotPage = new System.Windows.Forms.TabPage();
			this.plotSurface = new NPlot.Windows.PlotSurface2D();
			this.tablePage = new System.Windows.Forms.TabPage();
			this.gridView = new System.Windows.Forms.DataGridView();
			this.tabControl1.SuspendLayout();
			this.plotPage.SuspendLayout();
			this.tablePage.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.gridView)).BeginInit();
			this.SuspendLayout();
			// 
			// tabControl1
			// 
			this.tabControl1.Controls.Add(this.plotPage);
			this.tabControl1.Controls.Add(this.tablePage);
			this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.tabControl1.Location = new System.Drawing.Point(0, 0);
			this.tabControl1.Name = "tabControl1";
			this.tabControl1.SelectedIndex = 0;
			this.tabControl1.Size = new System.Drawing.Size(512, 500);
			this.tabControl1.TabIndex = 0;
			// 
			// plotPage
			// 
			this.plotPage.Controls.Add(this.plotSurface);
			this.plotPage.Location = new System.Drawing.Point(4, 22);
			this.plotPage.Name = "plotPage";
			this.plotPage.Padding = new System.Windows.Forms.Padding(3);
			this.plotPage.Size = new System.Drawing.Size(504, 474);
			this.plotPage.TabIndex = 0;
			this.plotPage.Text = "Plot";
			this.plotPage.UseVisualStyleBackColor = true;
			// 
			// plotSurface
			// 
			this.plotSurface.AutoScaleAutoGeneratedAxes = false;
			this.plotSurface.AutoScaleTitle = false;
			this.plotSurface.BackColor = System.Drawing.SystemColors.ControlLightLight;
			this.plotSurface.DateTimeToolTip = false;
			this.plotSurface.Dock = System.Windows.Forms.DockStyle.Fill;
			this.plotSurface.Legend = null;
			this.plotSurface.LegendZOrder = -1;
			this.plotSurface.Location = new System.Drawing.Point(3, 3);
			this.plotSurface.Name = "plotSurface";
			this.plotSurface.RightMenu = null;
			this.plotSurface.ShowCoordinates = true;
			this.plotSurface.Size = new System.Drawing.Size(498, 468);
			this.plotSurface.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
			this.plotSurface.TabIndex = 0;
			this.plotSurface.Text = "plotSurface2D1";
			this.plotSurface.Title = "";
			this.plotSurface.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
			this.plotSurface.XAxis1 = null;
			this.plotSurface.XAxis2 = null;
			this.plotSurface.YAxis1 = null;
			this.plotSurface.YAxis2 = null;
			// 
			// tablePage
			// 
			this.tablePage.Controls.Add(this.gridView);
			this.tablePage.Location = new System.Drawing.Point(4, 22);
			this.tablePage.Name = "tablePage";
			this.tablePage.Padding = new System.Windows.Forms.Padding(3);
			this.tablePage.Size = new System.Drawing.Size(504, 474);
			this.tablePage.TabIndex = 1;
			this.tablePage.Text = "Table";
			this.tablePage.UseVisualStyleBackColor = true;
			// 
			// gridView
			// 
			this.gridView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.gridView.Dock = System.Windows.Forms.DockStyle.Fill;
			this.gridView.Location = new System.Drawing.Point(3, 3);
			this.gridView.Name = "gridView";
			this.gridView.Size = new System.Drawing.Size(498, 468);
			this.gridView.TabIndex = 2;
			// 
			// DataVisualizer
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Controls.Add(this.tabControl1);
			this.Name = "DataVisualizer";
			this.Size = new System.Drawing.Size(512, 500);
			this.tabControl1.ResumeLayout(false);
			this.plotPage.ResumeLayout(false);
			this.tablePage.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.gridView)).EndInit();
			this.ResumeLayout(false);

		}

		#endregion

		private System.Windows.Forms.TabControl tabControl1;
		private System.Windows.Forms.TabPage plotPage;
		private System.Windows.Forms.TabPage tablePage;
		private NPlot.Windows.PlotSurface2D plotSurface;
		private System.Windows.Forms.DataGridView gridView;
	}
}
