namespace DesktopClient {
	partial class HeatLeakVisualizer {
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent() {
			this.plot = new NPlot.Windows.PlotSurface2D();
			this.SuspendLayout();
			// 
			// plot
			// 
			this.plot.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
						| System.Windows.Forms.AnchorStyles.Left)
						| System.Windows.Forms.AnchorStyles.Right)));
			this.plot.AutoScaleAutoGeneratedAxes = false;
			this.plot.AutoScaleTitle = false;
			this.plot.BackColor = System.Drawing.SystemColors.ControlLightLight;
			this.plot.DateTimeToolTip = false;
			this.plot.Legend = null;
			this.plot.LegendZOrder = -1;
			this.plot.Location = new System.Drawing.Point(-1, -1);
			this.plot.Name = "plot";
			this.plot.RightMenu = null;
			this.plot.ShowCoordinates = true;
			this.plot.Size = new System.Drawing.Size(524, 332);
			this.plot.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
			this.plot.TabIndex = 1;
			this.plot.Text = "plotSurface2D1";
			this.plot.Title = "";
			this.plot.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
			this.plot.XAxis1 = null;
			this.plot.XAxis2 = null;
			this.plot.YAxis1 = null;
			this.plot.YAxis2 = null;
			// 
			// HeatLeakVisualizer
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(522, 333);
			this.Controls.Add(this.plot);
			this.Name = "HeatLeakVisualizer";
			this.Text = "HeatLeakVisualizer";
			this.ResumeLayout(false);

		}

		#endregion

		private NPlot.Windows.PlotSurface2D plot;


	}
}