namespace DesktopClient {
	partial class SketchPad {
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent() {
			this.plotSurface = new NPlot.Windows.PlotSurface2D();
			this.clearButton = new System.Windows.Forms.Button();
			this.closeButton = new System.Windows.Forms.Button();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.crossSectionRadioButton = new System.Windows.Forms.RadioButton();
			this.strutLengthRadioButton = new System.Windows.Forms.RadioButton();
			this.powerFactorRadioButton = new System.Windows.Forms.RadioButton();
			this.autoScaleCheckbox = new System.Windows.Forms.CheckBox();
			this.groupBox1.SuspendLayout();
			this.SuspendLayout();
			// 
			// plotSurface
			// 
			this.plotSurface.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
						| System.Windows.Forms.AnchorStyles.Left)
						| System.Windows.Forms.AnchorStyles.Right)));
			this.plotSurface.AutoScaleAutoGeneratedAxes = false;
			this.plotSurface.AutoScaleTitle = false;
			this.plotSurface.BackColor = System.Drawing.SystemColors.ControlLightLight;
			this.plotSurface.DateTimeToolTip = false;
			this.plotSurface.Legend = null;
			this.plotSurface.LegendZOrder = -1;
			this.plotSurface.Location = new System.Drawing.Point(1, -1);
			this.plotSurface.Name = "plotSurface";
			this.plotSurface.RightMenu = null;
			this.plotSurface.ShowCoordinates = true;
			this.plotSurface.Size = new System.Drawing.Size(627, 368);
			this.plotSurface.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
			this.plotSurface.TabIndex = 0;
			this.plotSurface.Text = "plotSurface2D1";
			this.plotSurface.Title = "";
			this.plotSurface.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
			this.plotSurface.XAxis1 = null;
			this.plotSurface.XAxis2 = null;
			this.plotSurface.YAxis1 = null;
			this.plotSurface.YAxis2 = null;
			// 
			// clearButton
			// 
			this.clearButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
			this.clearButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.clearButton.Location = new System.Drawing.Point(458, 453);
			this.clearButton.Name = "clearButton";
			this.clearButton.Size = new System.Drawing.Size(75, 23);
			this.clearButton.TabIndex = 1;
			this.clearButton.Text = "Clear";
			this.clearButton.UseVisualStyleBackColor = true;
			this.clearButton.Click += new System.EventHandler(this.clearButton_Click);
			// 
			// closeButton
			// 
			this.closeButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
			this.closeButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.closeButton.Location = new System.Drawing.Point(539, 453);
			this.closeButton.Name = "closeButton";
			this.closeButton.Size = new System.Drawing.Size(75, 23);
			this.closeButton.TabIndex = 1;
			this.closeButton.Text = "Close";
			this.closeButton.UseVisualStyleBackColor = true;
			this.closeButton.Click += new System.EventHandler(this.closeButton_Click);
			// 
			// groupBox1
			// 
			this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
			this.groupBox1.Controls.Add(this.crossSectionRadioButton);
			this.groupBox1.Controls.Add(this.strutLengthRadioButton);
			this.groupBox1.Controls.Add(this.powerFactorRadioButton);
			this.groupBox1.Location = new System.Drawing.Point(264, 390);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(182, 95);
			this.groupBox1.TabIndex = 2;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "X Axis";
			// 
			// crossSectionRadioButton
			// 
			this.crossSectionRadioButton.AutoSize = true;
			this.crossSectionRadioButton.Location = new System.Drawing.Point(30, 62);
			this.crossSectionRadioButton.Name = "crossSectionRadioButton";
			this.crossSectionRadioButton.Size = new System.Drawing.Size(115, 17);
			this.crossSectionRadioButton.TabIndex = 2;
			this.crossSectionRadioButton.Text = "Strut Cross Section";
			this.crossSectionRadioButton.UseVisualStyleBackColor = true;
			this.crossSectionRadioButton.CheckedChanged += new System.EventHandler(this.checkbox_CheckedChanged);
			// 
			// strutLengthRadioButton
			// 
			this.strutLengthRadioButton.AutoSize = true;
			this.strutLengthRadioButton.Location = new System.Drawing.Point(30, 39);
			this.strutLengthRadioButton.Name = "strutLengthRadioButton";
			this.strutLengthRadioButton.Size = new System.Drawing.Size(83, 17);
			this.strutLengthRadioButton.TabIndex = 1;
			this.strutLengthRadioButton.Text = "Strut Length";
			this.strutLengthRadioButton.UseVisualStyleBackColor = true;
			this.strutLengthRadioButton.CheckedChanged += new System.EventHandler(this.checkbox_CheckedChanged);
			// 
			// powerFactorRadioButton
			// 
			this.powerFactorRadioButton.AutoSize = true;
			this.powerFactorRadioButton.Checked = true;
			this.powerFactorRadioButton.Location = new System.Drawing.Point(30, 16);
			this.powerFactorRadioButton.Name = "powerFactorRadioButton";
			this.powerFactorRadioButton.Size = new System.Drawing.Size(88, 17);
			this.powerFactorRadioButton.TabIndex = 0;
			this.powerFactorRadioButton.TabStop = true;
			this.powerFactorRadioButton.Text = "Power Factor";
			this.powerFactorRadioButton.UseVisualStyleBackColor = true;
			this.powerFactorRadioButton.CheckedChanged += new System.EventHandler(this.checkbox_CheckedChanged);
			// 
			// autoScaleCheckbox
			// 
			this.autoScaleCheckbox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
			this.autoScaleCheckbox.AutoSize = true;
			this.autoScaleCheckbox.Location = new System.Drawing.Point(458, 406);
			this.autoScaleCheckbox.Name = "autoScaleCheckbox";
			this.autoScaleCheckbox.Size = new System.Drawing.Size(78, 17);
			this.autoScaleCheckbox.TabIndex = 3;
			this.autoScaleCheckbox.Text = "Auto Scale";
			this.autoScaleCheckbox.UseVisualStyleBackColor = true;
			this.autoScaleCheckbox.CheckedChanged += new System.EventHandler(this.autoScaleCheckbox_CheckedChanged);
			// 
			// SketchPad
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(626, 488);
			this.Controls.Add(this.autoScaleCheckbox);
			this.Controls.Add(this.groupBox1);
			this.Controls.Add(this.closeButton);
			this.Controls.Add(this.clearButton);
			this.Controls.Add(this.plotSurface);
			this.Name = "SketchPad";
			this.Text = "SketchPad";
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private NPlot.Windows.PlotSurface2D plotSurface;
		private System.Windows.Forms.Button clearButton;
		private System.Windows.Forms.Button closeButton;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.RadioButton crossSectionRadioButton;
		private System.Windows.Forms.RadioButton strutLengthRadioButton;
		private System.Windows.Forms.RadioButton powerFactorRadioButton;
		private System.Windows.Forms.CheckBox autoScaleCheckbox;
	}
}