//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.312.
// 
#pragma warning disable 1591

namespace DesktopClient.CoolIt_Web_Service {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.engr.wisc.edu/cryo")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CryoObject))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCoolersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMaterialsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SimulateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SimulatePFOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::DesktopClient.Properties.Settings.Default.DesktopClient_CoolIt_Web_Service_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCoolersCompletedEventHandler GetCoolersCompleted;
        
        /// <remarks/>
        public event GetMaterialsCompletedEventHandler GetMaterialsCompleted;
        
        /// <remarks/>
        public event SimulateCompletedEventHandler SimulateCompleted;
        
        /// <remarks/>
        public event SimulatePFCompletedEventHandler SimulatePFCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.engr.wisc.edu/cryo/GetCoolers", RequestNamespace="http://www.engr.wisc.edu/cryo", ResponseNamespace="http://www.engr.wisc.edu/cryo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cooler[] GetCoolers() {
            object[] results = this.Invoke("GetCoolers", new object[0]);
            return ((Cooler[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCoolersAsync() {
            this.GetCoolersAsync(null);
        }
        
        /// <remarks/>
        public void GetCoolersAsync(object userState) {
            if ((this.GetCoolersOperationCompleted == null)) {
                this.GetCoolersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCoolersOperationCompleted);
            }
            this.InvokeAsync("GetCoolers", new object[0], this.GetCoolersOperationCompleted, userState);
        }
        
        private void OnGetCoolersOperationCompleted(object arg) {
            if ((this.GetCoolersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCoolersCompleted(this, new GetCoolersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.engr.wisc.edu/cryo/GetMaterials", RequestNamespace="http://www.engr.wisc.edu/cryo", ResponseNamespace="http://www.engr.wisc.edu/cryo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Material[] GetMaterials() {
            object[] results = this.Invoke("GetMaterials", new object[0]);
            return ((Material[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMaterialsAsync() {
            this.GetMaterialsAsync(null);
        }
        
        /// <remarks/>
        public void GetMaterialsAsync(object userState) {
            if ((this.GetMaterialsOperationCompleted == null)) {
                this.GetMaterialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMaterialsOperationCompleted);
            }
            this.InvokeAsync("GetMaterials", new object[0], this.GetMaterialsOperationCompleted, userState);
        }
        
        private void OnGetMaterialsOperationCompleted(object arg) {
            if ((this.GetMaterialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMaterialsCompleted(this, new GetMaterialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.engr.wisc.edu/cryo/Simulate", RequestNamespace="http://www.engr.wisc.edu/cryo", ResponseNamespace="http://www.engr.wisc.edu/cryo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Simulate(double length, double crossSection, string materialName, string coolerName) {
            object[] results = this.Invoke("Simulate", new object[] {
                        length,
                        crossSection,
                        materialName,
                        coolerName});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void SimulateAsync(double length, double crossSection, string materialName, string coolerName) {
            this.SimulateAsync(length, crossSection, materialName, coolerName, null);
        }
        
        /// <remarks/>
        public void SimulateAsync(double length, double crossSection, string materialName, string coolerName, object userState) {
            if ((this.SimulateOperationCompleted == null)) {
                this.SimulateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSimulateOperationCompleted);
            }
            this.InvokeAsync("Simulate", new object[] {
                        length,
                        crossSection,
                        materialName,
                        coolerName}, this.SimulateOperationCompleted, userState);
        }
        
        private void OnSimulateOperationCompleted(object arg) {
            if ((this.SimulateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SimulateCompleted(this, new SimulateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.engr.wisc.edu/cryo/SimulatePF", RequestNamespace="http://www.engr.wisc.edu/cryo", ResponseNamespace="http://www.engr.wisc.edu/cryo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double SimulatePF(double length, double crossSection, string materialName, string coolerName, double powerFactor) {
            object[] results = this.Invoke("SimulatePF", new object[] {
                        length,
                        crossSection,
                        materialName,
                        coolerName,
                        powerFactor});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void SimulatePFAsync(double length, double crossSection, string materialName, string coolerName, double powerFactor) {
            this.SimulatePFAsync(length, crossSection, materialName, coolerName, powerFactor, null);
        }
        
        /// <remarks/>
        public void SimulatePFAsync(double length, double crossSection, string materialName, string coolerName, double powerFactor, object userState) {
            if ((this.SimulatePFOperationCompleted == null)) {
                this.SimulatePFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSimulatePFOperationCompleted);
            }
            this.InvokeAsync("SimulatePF", new object[] {
                        length,
                        crossSection,
                        materialName,
                        coolerName,
                        powerFactor}, this.SimulatePFOperationCompleted, userState);
        }
        
        private void OnSimulatePFOperationCompleted(object arg) {
            if ((this.SimulatePFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SimulatePFCompleted(this, new SimulatePFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.engr.wisc.edu/cryo")]
    public partial class Cooler : CryoObject {
        
        private DataPoint[] cPMField;
        
        /// <remarks/>
        public DataPoint[] CPM {
            get {
                return this.cPMField;
            }
            set {
                this.cPMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.engr.wisc.edu/cryo")]
    public partial class DataPoint {
        
        private double tempField;
        
        private double dataField;
        
        /// <remarks/>
        public double temp {
            get {
                return this.tempField;
            }
            set {
                this.tempField = value;
            }
        }
        
        /// <remarks/>
        public double data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Material))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cooler))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.engr.wisc.edu/cryo")]
    public abstract partial class CryoObject {
        
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.engr.wisc.edu/cryo")]
    public partial class Material : CryoObject {
        
        private DataPoint[] mpField;
        
        /// <remarks/>
        public DataPoint[] MP {
            get {
                return this.mpField;
            }
            set {
                this.mpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void GetCoolersCompletedEventHandler(object sender, GetCoolersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCoolersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCoolersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cooler[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cooler[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void GetMaterialsCompletedEventHandler(object sender, GetMaterialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMaterialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMaterialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Material[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Material[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void SimulateCompletedEventHandler(object sender, SimulateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimulateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SimulateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void SimulatePFCompletedEventHandler(object sender, SimulatePFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimulatePFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SimulatePFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591