//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4200.
// 
#pragma warning disable 1591

namespace DesktopClient.CoolIt_Service {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CoolIt_ServiceSoap", Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CryoObject))]
    public partial class CoolIt_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NewLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasCapabilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback TryMathGateOperationCompleted;
        
        private System.Threading.SendOrPostCallback WebServiceVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CryolibVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCoolersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMaterialsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProblemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMathGatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSpecificPowerDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetStrutOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetCoolerOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetProblemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOptimalSolutionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RunOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFeedbackOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CoolIt_Service() {
            this.Url = global::DesktopClient.Properties.Settings.Default.DesktopClient_CoolIt_Service_CoolIt_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NewLoginCompletedEventHandler NewLoginCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event HasCapabilityCompletedEventHandler HasCapabilityCompleted;
        
        /// <remarks/>
        public event TryMathGateCompletedEventHandler TryMathGateCompleted;
        
        /// <remarks/>
        public event WebServiceVersionCompletedEventHandler WebServiceVersionCompleted;
        
        /// <remarks/>
        public event CryolibVersionCompletedEventHandler CryolibVersionCompleted;
        
        /// <remarks/>
        public event GetCoolersCompletedEventHandler GetCoolersCompleted;
        
        /// <remarks/>
        public event GetMaterialsCompletedEventHandler GetMaterialsCompleted;
        
        /// <remarks/>
        public event GetProblemsCompletedEventHandler GetProblemsCompleted;
        
        /// <remarks/>
        public event GetMathGatesCompletedEventHandler GetMathGatesCompleted;
        
        /// <remarks/>
        public event GetSpecificPowerDataCompletedEventHandler GetSpecificPowerDataCompleted;
        
        /// <remarks/>
        public event SetStrutCompletedEventHandler SetStrutCompleted;
        
        /// <remarks/>
        public event SetCoolerCompletedEventHandler SetCoolerCompleted;
        
        /// <remarks/>
        public event SetProblemCompletedEventHandler SetProblemCompleted;
        
        /// <remarks/>
        public event GetOptimalSolutionsCompletedEventHandler GetOptimalSolutionsCompleted;
        
        /// <remarks/>
        public event RunCompletedEventHandler RunCompleted;
        
        /// <remarks/>
        public event GetFeedbackCompletedEventHandler GetFeedbackCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/NewLogin", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool NewLogin(string emailAddr) {
            object[] results = this.Invoke("NewLogin", new object[] {
                        emailAddr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void NewLoginAsync(string emailAddr) {
            this.NewLoginAsync(emailAddr, null);
        }
        
        /// <remarks/>
        public void NewLoginAsync(string emailAddr, object userState) {
            if ((this.NewLoginOperationCompleted == null)) {
                this.NewLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewLoginOperationCompleted);
            }
            this.InvokeAsync("NewLogin", new object[] {
                        emailAddr}, this.NewLoginOperationCompleted, userState);
        }
        
        private void OnNewLoginOperationCompleted(object arg) {
            if ((this.NewLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewLoginCompleted(this, new NewLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/Login", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Login(string emailAddr) {
            object[] results = this.Invoke("Login", new object[] {
                        emailAddr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string emailAddr) {
            this.LoginAsync(emailAddr, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string emailAddr, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        emailAddr}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/HasCapability", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HasCapability(CAPABILITY requestedCapability) {
            object[] results = this.Invoke("HasCapability", new object[] {
                        requestedCapability});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HasCapabilityAsync(CAPABILITY requestedCapability) {
            this.HasCapabilityAsync(requestedCapability, null);
        }
        
        /// <remarks/>
        public void HasCapabilityAsync(CAPABILITY requestedCapability, object userState) {
            if ((this.HasCapabilityOperationCompleted == null)) {
                this.HasCapabilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasCapabilityOperationCompleted);
            }
            this.InvokeAsync("HasCapability", new object[] {
                        requestedCapability}, this.HasCapabilityOperationCompleted, userState);
        }
        
        private void OnHasCapabilityOperationCompleted(object arg) {
            if ((this.HasCapabilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasCapabilityCompleted(this, new HasCapabilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/TryMathGate", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TryMathGate(string gateName, double[] answers) {
            object[] results = this.Invoke("TryMathGate", new object[] {
                        gateName,
                        answers});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void TryMathGateAsync(string gateName, double[] answers) {
            this.TryMathGateAsync(gateName, answers, null);
        }
        
        /// <remarks/>
        public void TryMathGateAsync(string gateName, double[] answers, object userState) {
            if ((this.TryMathGateOperationCompleted == null)) {
                this.TryMathGateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTryMathGateOperationCompleted);
            }
            this.InvokeAsync("TryMathGate", new object[] {
                        gateName,
                        answers}, this.TryMathGateOperationCompleted, userState);
        }
        
        private void OnTryMathGateOperationCompleted(object arg) {
            if ((this.TryMathGateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TryMathGateCompleted(this, new TryMathGateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/WebServiceVersion", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MyAssemblyInfo WebServiceVersion() {
            object[] results = this.Invoke("WebServiceVersion", new object[0]);
            return ((MyAssemblyInfo)(results[0]));
        }
        
        /// <remarks/>
        public void WebServiceVersionAsync() {
            this.WebServiceVersionAsync(null);
        }
        
        /// <remarks/>
        public void WebServiceVersionAsync(object userState) {
            if ((this.WebServiceVersionOperationCompleted == null)) {
                this.WebServiceVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWebServiceVersionOperationCompleted);
            }
            this.InvokeAsync("WebServiceVersion", new object[0], this.WebServiceVersionOperationCompleted, userState);
        }
        
        private void OnWebServiceVersionOperationCompleted(object arg) {
            if ((this.WebServiceVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WebServiceVersionCompleted(this, new WebServiceVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/CryolibVersion", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MyAssemblyInfo CryolibVersion() {
            object[] results = this.Invoke("CryolibVersion", new object[0]);
            return ((MyAssemblyInfo)(results[0]));
        }
        
        /// <remarks/>
        public void CryolibVersionAsync() {
            this.CryolibVersionAsync(null);
        }
        
        /// <remarks/>
        public void CryolibVersionAsync(object userState) {
            if ((this.CryolibVersionOperationCompleted == null)) {
                this.CryolibVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCryolibVersionOperationCompleted);
            }
            this.InvokeAsync("CryolibVersion", new object[0], this.CryolibVersionOperationCompleted, userState);
        }
        
        private void OnCryolibVersionOperationCompleted(object arg) {
            if ((this.CryolibVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CryolibVersionCompleted(this, new CryolibVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/GetCoolers", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cooler[] GetCoolers() {
            object[] results = this.Invoke("GetCoolers", new object[0]);
            return ((Cooler[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCoolersAsync() {
            this.GetCoolersAsync(null);
        }
        
        /// <remarks/>
        public void GetCoolersAsync(object userState) {
            if ((this.GetCoolersOperationCompleted == null)) {
                this.GetCoolersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCoolersOperationCompleted);
            }
            this.InvokeAsync("GetCoolers", new object[0], this.GetCoolersOperationCompleted, userState);
        }
        
        private void OnGetCoolersOperationCompleted(object arg) {
            if ((this.GetCoolersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCoolersCompleted(this, new GetCoolersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/GetMaterials", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Material[] GetMaterials() {
            object[] results = this.Invoke("GetMaterials", new object[0]);
            return ((Material[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMaterialsAsync() {
            this.GetMaterialsAsync(null);
        }
        
        /// <remarks/>
        public void GetMaterialsAsync(object userState) {
            if ((this.GetMaterialsOperationCompleted == null)) {
                this.GetMaterialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMaterialsOperationCompleted);
            }
            this.InvokeAsync("GetMaterials", new object[0], this.GetMaterialsOperationCompleted, userState);
        }
        
        private void OnGetMaterialsOperationCompleted(object arg) {
            if ((this.GetMaterialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMaterialsCompleted(this, new GetMaterialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/GetProblems", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Problem[] GetProblems() {
            object[] results = this.Invoke("GetProblems", new object[0]);
            return ((Problem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProblemsAsync() {
            this.GetProblemsAsync(null);
        }
        
        /// <remarks/>
        public void GetProblemsAsync(object userState) {
            if ((this.GetProblemsOperationCompleted == null)) {
                this.GetProblemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProblemsOperationCompleted);
            }
            this.InvokeAsync("GetProblems", new object[0], this.GetProblemsOperationCompleted, userState);
        }
        
        private void OnGetProblemsOperationCompleted(object arg) {
            if ((this.GetProblemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProblemsCompleted(this, new GetProblemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/GetMathGates", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MathGate[] GetMathGates() {
            object[] results = this.Invoke("GetMathGates", new object[0]);
            return ((MathGate[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMathGatesAsync() {
            this.GetMathGatesAsync(null);
        }
        
        /// <remarks/>
        public void GetMathGatesAsync(object userState) {
            if ((this.GetMathGatesOperationCompleted == null)) {
                this.GetMathGatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMathGatesOperationCompleted);
            }
            this.InvokeAsync("GetMathGates", new object[0], this.GetMathGatesOperationCompleted, userState);
        }
        
        private void OnGetMathGatesOperationCompleted(object arg) {
            if ((this.GetMathGatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMathGatesCompleted(this, new GetMathGatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/GetSpecificPowerData", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataPoint[] GetSpecificPowerData() {
            object[] results = this.Invoke("GetSpecificPowerData", new object[0]);
            return ((DataPoint[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSpecificPowerDataAsync() {
            this.GetSpecificPowerDataAsync(null);
        }
        
        /// <remarks/>
        public void GetSpecificPowerDataAsync(object userState) {
            if ((this.GetSpecificPowerDataOperationCompleted == null)) {
                this.GetSpecificPowerDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSpecificPowerDataOperationCompleted);
            }
            this.InvokeAsync("GetSpecificPowerData", new object[0], this.GetSpecificPowerDataOperationCompleted, userState);
        }
        
        private void OnGetSpecificPowerDataOperationCompleted(object arg) {
            if ((this.GetSpecificPowerDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSpecificPowerDataCompleted(this, new GetSpecificPowerDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/SetStrut", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetStrut(string materialName, double length, double crossSection) {
            this.Invoke("SetStrut", new object[] {
                        materialName,
                        length,
                        crossSection});
        }
        
        /// <remarks/>
        public void SetStrutAsync(string materialName, double length, double crossSection) {
            this.SetStrutAsync(materialName, length, crossSection, null);
        }
        
        /// <remarks/>
        public void SetStrutAsync(string materialName, double length, double crossSection, object userState) {
            if ((this.SetStrutOperationCompleted == null)) {
                this.SetStrutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetStrutOperationCompleted);
            }
            this.InvokeAsync("SetStrut", new object[] {
                        materialName,
                        length,
                        crossSection}, this.SetStrutOperationCompleted, userState);
        }
        
        private void OnSetStrutOperationCompleted(object arg) {
            if ((this.SetStrutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetStrutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/SetCooler", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetCooler(string name, double powerFactor) {
            this.Invoke("SetCooler", new object[] {
                        name,
                        powerFactor});
        }
        
        /// <remarks/>
        public void SetCoolerAsync(string name, double powerFactor) {
            this.SetCoolerAsync(name, powerFactor, null);
        }
        
        /// <remarks/>
        public void SetCoolerAsync(string name, double powerFactor, object userState) {
            if ((this.SetCoolerOperationCompleted == null)) {
                this.SetCoolerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetCoolerOperationCompleted);
            }
            this.InvokeAsync("SetCooler", new object[] {
                        name,
                        powerFactor}, this.SetCoolerOperationCompleted, userState);
        }
        
        private void OnSetCoolerOperationCompleted(object arg) {
            if ((this.SetCoolerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetCoolerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/SetProblem", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetProblem(string name) {
            object[] results = this.Invoke("SetProblem", new object[] {
                        name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetProblemAsync(string name) {
            this.SetProblemAsync(name, null);
        }
        
        /// <remarks/>
        public void SetProblemAsync(string name, object userState) {
            if ((this.SetProblemOperationCompleted == null)) {
                this.SetProblemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetProblemOperationCompleted);
            }
            this.InvokeAsync("SetProblem", new object[] {
                        name}, this.SetProblemOperationCompleted, userState);
        }
        
        private void OnSetProblemOperationCompleted(object arg) {
            if ((this.SetProblemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetProblemCompleted(this, new SetProblemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/GetOptimalSolutions", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Solution[] GetOptimalSolutions() {
            object[] results = this.Invoke("GetOptimalSolutions", new object[0]);
            return ((Solution[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOptimalSolutionsAsync() {
            this.GetOptimalSolutionsAsync(null);
        }
        
        /// <remarks/>
        public void GetOptimalSolutionsAsync(object userState) {
            if ((this.GetOptimalSolutionsOperationCompleted == null)) {
                this.GetOptimalSolutionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOptimalSolutionsOperationCompleted);
            }
            this.InvokeAsync("GetOptimalSolutions", new object[0], this.GetOptimalSolutionsOperationCompleted, userState);
        }
        
        private void OnGetOptimalSolutionsOperationCompleted(object arg) {
            if ((this.GetOptimalSolutionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOptimalSolutionsCompleted(this, new GetOptimalSolutionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/Run", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public State Run() {
            object[] results = this.Invoke("Run", new object[0]);
            return ((State)(results[0]));
        }
        
        /// <remarks/>
        public void RunAsync() {
            this.RunAsync(null);
        }
        
        /// <remarks/>
        public void RunAsync(object userState) {
            if ((this.RunOperationCompleted == null)) {
                this.RunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRunOperationCompleted);
            }
            this.InvokeAsync("Run", new object[0], this.RunOperationCompleted, userState);
        }
        
        private void OnRunOperationCompleted(object arg) {
            if ((this.RunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RunCompleted(this, new RunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wisc.edu/doit/ls/coolit/GetFeedback", RequestNamespace="http://www.wisc.edu/doit/ls/coolit/", ResponseNamespace="http://www.wisc.edu/doit/ls/coolit/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Feedback GetFeedback() {
            object[] results = this.Invoke("GetFeedback", new object[0]);
            return ((Feedback)(results[0]));
        }
        
        /// <remarks/>
        public void GetFeedbackAsync() {
            this.GetFeedbackAsync(null);
        }
        
        /// <remarks/>
        public void GetFeedbackAsync(object userState) {
            if ((this.GetFeedbackOperationCompleted == null)) {
                this.GetFeedbackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFeedbackOperationCompleted);
            }
            this.InvokeAsync("GetFeedback", new object[0], this.GetFeedbackOperationCompleted, userState);
        }
        
        private void OnGetFeedbackOperationCompleted(object arg) {
            if ((this.GetFeedbackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFeedbackCompleted(this, new GetFeedbackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public enum CAPABILITY {
        
        /// <remarks/>
        CP_VS_HEAT_LEAK_GRAPH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class MyAssemblyInfo {
        
        private string majorField;
        
        private string minorField;
        
        private string buildField;
        
        private string revisionField;
        
        /// <remarks/>
        public string Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        public string Minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
            }
        }
        
        /// <remarks/>
        public string Build {
            get {
                return this.buildField;
            }
            set {
                this.buildField = value;
            }
        }
        
        /// <remarks/>
        public string Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class Feedback {
        
        private string textField;
        
        private string cutScreenField;
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string CutScreen {
            get {
                return this.cutScreenField;
            }
            set {
                this.cutScreenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class State {
        
        private double temperatureField;
        
        private int numStrutsField;
        
        private double lengthField;
        
        private double crossSectionField;
        
        private string materialNameField;
        
        private double powerFactorField;
        
        private string coolerNameField;
        
        private double inputPowerField;
        
        private double costField;
        
        private double stressLimitField;
        
        private string problemNameField;
        
        private bool isValidSolutionField;
        
        /// <remarks/>
        public double temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
            }
        }
        
        /// <remarks/>
        public int numStruts {
            get {
                return this.numStrutsField;
            }
            set {
                this.numStrutsField = value;
            }
        }
        
        /// <remarks/>
        public double length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public double crossSection {
            get {
                return this.crossSectionField;
            }
            set {
                this.crossSectionField = value;
            }
        }
        
        /// <remarks/>
        public string materialName {
            get {
                return this.materialNameField;
            }
            set {
                this.materialNameField = value;
            }
        }
        
        /// <remarks/>
        public double powerFactor {
            get {
                return this.powerFactorField;
            }
            set {
                this.powerFactorField = value;
            }
        }
        
        /// <remarks/>
        public string coolerName {
            get {
                return this.coolerNameField;
            }
            set {
                this.coolerNameField = value;
            }
        }
        
        /// <remarks/>
        public double inputPower {
            get {
                return this.inputPowerField;
            }
            set {
                this.inputPowerField = value;
            }
        }
        
        /// <remarks/>
        public double cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        public double stressLimit {
            get {
                return this.stressLimitField;
            }
            set {
                this.stressLimitField = value;
            }
        }
        
        /// <remarks/>
        public string problemName {
            get {
                return this.problemNameField;
            }
            set {
                this.problemNameField = value;
            }
        }
        
        /// <remarks/>
        public bool isValidSolution {
            get {
                return this.isValidSolutionField;
            }
            set {
                this.isValidSolutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class Solution {
        
        private string problemNameField;
        
        private string coolerNameField;
        
        private double coolerPowerFactorField;
        
        private string materialNameField;
        
        private double strutCrossSectionField;
        
        private double strutLengthField;
        
        private double costField;
        
        /// <remarks/>
        public string ProblemName {
            get {
                return this.problemNameField;
            }
            set {
                this.problemNameField = value;
            }
        }
        
        /// <remarks/>
        public string CoolerName {
            get {
                return this.coolerNameField;
            }
            set {
                this.coolerNameField = value;
            }
        }
        
        /// <remarks/>
        public double CoolerPowerFactor {
            get {
                return this.coolerPowerFactorField;
            }
            set {
                this.coolerPowerFactorField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialName {
            get {
                return this.materialNameField;
            }
            set {
                this.materialNameField = value;
            }
        }
        
        /// <remarks/>
        public double StrutCrossSection {
            get {
                return this.strutCrossSectionField;
            }
            set {
                this.strutCrossSectionField = value;
            }
        }
        
        /// <remarks/>
        public double StrutLength {
            get {
                return this.strutLengthField;
            }
            set {
                this.strutLengthField = value;
            }
        }
        
        /// <remarks/>
        public double Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class MathGateProblem {
        
        private string descriptionField;
        
        private double correctAnswerField;
        
        private double precisionRequiredField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double CorrectAnswer {
            get {
                return this.correctAnswerField;
            }
            set {
                this.correctAnswerField = value;
            }
        }
        
        /// <remarks/>
        public double PrecisionRequired {
            get {
                return this.precisionRequiredField;
            }
            set {
                this.precisionRequiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class MathGate {
        
        private string nameField;
        
        private int idField;
        
        private MathGateProblem[] problemsField;
        
        private CAPABILITY capabilityField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public MathGateProblem[] Problems {
            get {
                return this.problemsField;
            }
            set {
                this.problemsField = value;
            }
        }
        
        /// <remarks/>
        public CAPABILITY Capability {
            get {
                return this.capabilityField;
            }
            set {
                this.capabilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class PickerImageCollection {
        
        private string baseNameField;
        
        private int lengthField;
        
        private int widthField;
        
        /// <remarks/>
        public string BaseName {
            get {
                return this.baseNameField;
            }
            set {
                this.baseNameField = value;
            }
        }
        
        /// <remarks/>
        public int Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class ProblemImageCollection {
        
        private string baseURIField;
        
        private string introField;
        
        private string successField;
        
        private string failPowerLimitField;
        
        private string failTooHotField;
        
        private string failStrutBreaksField;
        
        private PickerImageCollection pickerImageCollectionField;
        
        /// <remarks/>
        public string BaseURI {
            get {
                return this.baseURIField;
            }
            set {
                this.baseURIField = value;
            }
        }
        
        /// <remarks/>
        public string Intro {
            get {
                return this.introField;
            }
            set {
                this.introField = value;
            }
        }
        
        /// <remarks/>
        public string Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string FailPowerLimit {
            get {
                return this.failPowerLimitField;
            }
            set {
                this.failPowerLimitField = value;
            }
        }
        
        /// <remarks/>
        public string FailTooHot {
            get {
                return this.failTooHotField;
            }
            set {
                this.failTooHotField = value;
            }
        }
        
        /// <remarks/>
        public string FailStrutBreaks {
            get {
                return this.failStrutBreaksField;
            }
            set {
                this.failStrutBreaksField = value;
            }
        }
        
        /// <remarks/>
        public PickerImageCollection PickerImageCollection {
            get {
                return this.pickerImageCollectionField;
            }
            set {
                this.pickerImageCollectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class Constraint {
        
        private VALUE valueField;
        
        private OP opField;
        
        private double targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VALUE Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OP Op {
            get {
                return this.opField;
            }
            set {
                this.opField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public enum VALUE {
        
        /// <remarks/>
        FORCE_LIMIT,
        
        /// <remarks/>
        INPUT_POWER,
        
        /// <remarks/>
        TEMP,
        
        /// <remarks/>
        COST,
        
        /// <remarks/>
        STRUT_LENGTH,
        
        /// <remarks/>
        STRUT_CROSS_SECTION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public enum OP {
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LE,
        
        /// <remarks/>
        EQ,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        GT,
        
        /// <remarks/>
        NE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class Problem {
        
        private string descriptionField;
        
        private double monetaryIncentiveField;
        
        private double heatLeakField;
        
        private SupportMode supportModeField;
        
        private int supportNumberField;
        
        private Constraint[] constraintsField;
        
        private ProblemImageCollection imageCollectionField;
        
        private bool solvedField;
        
        private string nameField;
        
        private int idField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double MonetaryIncentive {
            get {
                return this.monetaryIncentiveField;
            }
            set {
                this.monetaryIncentiveField = value;
            }
        }
        
        /// <remarks/>
        public double HeatLeak {
            get {
                return this.heatLeakField;
            }
            set {
                this.heatLeakField = value;
            }
        }
        
        /// <remarks/>
        public SupportMode SupportMode {
            get {
                return this.supportModeField;
            }
            set {
                this.supportModeField = value;
            }
        }
        
        /// <remarks/>
        public int SupportNumber {
            get {
                return this.supportNumberField;
            }
            set {
                this.supportNumberField = value;
            }
        }
        
        /// <remarks/>
        public Constraint[] Constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
        
        /// <remarks/>
        public ProblemImageCollection ImageCollection {
            get {
                return this.imageCollectionField;
            }
            set {
                this.imageCollectionField = value;
            }
        }
        
        /// <remarks/>
        public bool Solved {
            get {
                return this.solvedField;
            }
            set {
                this.solvedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public enum SupportMode {
        
        /// <remarks/>
        COMPRESSION,
        
        /// <remarks/>
        TENSION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class DataPoint {
        
        private double tempField;
        
        private double dataField;
        
        /// <remarks/>
        public double temp {
            get {
                return this.tempField;
            }
            set {
                this.tempField = value;
            }
        }
        
        /// <remarks/>
        public double data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Material))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cooler))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public abstract partial class CryoObject {
        
        private string nameField;
        
        private int idField;
        
        private double priceField;
        
        private string priceUnitField;
        
        private string currencyUnitField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string priceUnit {
            get {
                return this.priceUnitField;
            }
            set {
                this.priceUnitField = value;
            }
        }
        
        /// <remarks/>
        public string currencyUnit {
            get {
                return this.currencyUnitField;
            }
            set {
                this.currencyUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class Material : CryoObject {
        
        private double yieldStrengthField;
        
        private DataPoint[] mpField;
        
        private DataPoint[] integratedThermalConductivityField;
        
        /// <remarks/>
        public double yieldStrength {
            get {
                return this.yieldStrengthField;
            }
            set {
                this.yieldStrengthField = value;
            }
        }
        
        /// <remarks/>
        public DataPoint[] MP {
            get {
                return this.mpField;
            }
            set {
                this.mpField = value;
            }
        }
        
        /// <remarks/>
        public DataPoint[] IntegratedThermalConductivity {
            get {
                return this.integratedThermalConductivityField;
            }
            set {
                this.integratedThermalConductivityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wisc.edu/doit/ls/coolit/")]
    public partial class Cooler : CryoObject {
        
        private DataPoint[] cPMField;
        
        /// <remarks/>
        public DataPoint[] CPM {
            get {
                return this.cPMField;
            }
            set {
                this.cPMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void NewLoginCompletedEventHandler(object sender, NewLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void HasCapabilityCompletedEventHandler(object sender, HasCapabilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasCapabilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasCapabilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void TryMathGateCompletedEventHandler(object sender, TryMathGateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TryMathGateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TryMathGateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void WebServiceVersionCompletedEventHandler(object sender, WebServiceVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebServiceVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WebServiceVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MyAssemblyInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MyAssemblyInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void CryolibVersionCompletedEventHandler(object sender, CryolibVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CryolibVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CryolibVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MyAssemblyInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MyAssemblyInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetCoolersCompletedEventHandler(object sender, GetCoolersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCoolersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCoolersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cooler[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cooler[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetMaterialsCompletedEventHandler(object sender, GetMaterialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMaterialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMaterialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Material[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Material[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetProblemsCompletedEventHandler(object sender, GetProblemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProblemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProblemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Problem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Problem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetMathGatesCompletedEventHandler(object sender, GetMathGatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMathGatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMathGatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MathGate[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MathGate[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetSpecificPowerDataCompletedEventHandler(object sender, GetSpecificPowerDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSpecificPowerDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSpecificPowerDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataPoint[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataPoint[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void SetStrutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void SetCoolerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void SetProblemCompletedEventHandler(object sender, SetProblemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetProblemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetProblemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetOptimalSolutionsCompletedEventHandler(object sender, GetOptimalSolutionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOptimalSolutionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOptimalSolutionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Solution[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Solution[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void RunCompletedEventHandler(object sender, RunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public State Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((State)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetFeedbackCompletedEventHandler(object sender, GetFeedbackCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFeedbackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFeedbackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Feedback Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Feedback)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591